name = "epgs-reserves-ical"
main = "src/index.ts"
compatibility_date = "2024-11-13"
routes = [
    { pattern = "update-epgs-ical.hiroxto.net", custom_domain = true }
]

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "EPGS_ICAL_BUCKET"
bucket_name = "epgs-ical-bucket"
preview_bucket_name = "epgs-ical-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
